---
abstract: 'Light-weight database patch utility'
author:
  - 'Chris Tijerina'
build_requires:
  Data::Dumper: '0'
  File::Temp: '0'
  FindBin: '0'
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Deployer
provides:
  DBIx::Deployer:
    file: lib/DBIx/Deployer.pm
    version: v1.2.0
  DBIx::Deployer::Patch:
    file: lib/DBIx/Deployer.pm
    version: v1.2.0
requires:
  DBD::SQLite: '0'
  DBI: '0'
  Data::Printer: '0'
  Digest::MD5: '0'
  JSON::XS: '0'
  Modern::Perl: '0'
  Moops: '0'
  Term::ANSIColor: '0'
  autodie: '0'
  perl: v5.14.2
resources:
  bugtracker: https://github.com/Camspi/DBIx-Deployer/issues
  homepage: https://github.com/Camspi/DBIx-Deployer
  repository: https://github.com/Camspi/DBIx-Deployer.git
version: v1.2.0
x_contributors:
  - 'Camspi <amarus18@hotmail.com>'
  - 'Chris Tijerina <ctijerina@emortgagelogic.com>'
  - 'lbeesley <lindsey.beesley@gmail.com>'
x_serialization_backend: 'YAML::Tiny version 1.70'
